### ISSUE TITLE
Windows builds fail on master

### ISSUE THREAD

**Issue by mbargull** [conda-forge/lief-feedstock#11]
```
2020-07-29T19:34:40.0295905Z import: 'lief'
2020-07-29T19:34:40.0525917Z Fatal Python error: PyThreadState_Get: no current thread
2020-07-29T19:34:40.0527722Z 
2020-07-29T19:34:42.7685337Z Tests failed for py-lief-0.10.1-py37h1834ac0_0.tar.bz2 - moving package to D:\bld\broken
```
Successful run from gh-10:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=185904
[https------dev.azure.com--conda-forge--84710dde-1620-425b-80d0-4cf5baca359d--_apis--build--builds--185904--logs--31.log](https://github.com/conda-forge/lief-feedstock/files/4997233/https------dev.azure.com--conda-forge--84710dde-1620-425b-80d0-4cf5baca359d--_apis--build--builds--185904--logs--31.log)
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/185904/logs/31

Failed run on `master`:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=185926
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/185926/logs/51
[https------dev.azure.com--conda-forge--84710dde-1620-425b-80d0-4cf5baca359d--_apis--build--builds--185926--logs--51.log](https://github.com/conda-forge/lief-feedstock/files/4997236/https------dev.azure.com--conda-forge--84710dde-1620-425b-80d0-4cf5baca359d--_apis--build--builds--185926--logs--51.log)

----
The build from gh-10 failed after merging to `master`. I restarted it today, but still the same error.
It's a bit strange that we get this failure now with 3.7 and not 3.8 as we did before.

**Comment by isuruf** [comment]
Maybe the patch that we reverted in 3.8 got backported to 3.7?

**Comment by mbargull** [comment]
Ah, good call. Will check.

**Comment by mbargull** [comment]
Hm, doesn't look like it did:
https://github.com/python/cpython/blob/v3.7.8/Python/dynload_win.c#L221

(Assuming we are talking about https://github.com/conda-forge/python-feedstock/blob/cf7ba76a05cbf67883306ae2a83d3c626b94f172/recipe/patches/0026-Revert-part-of-https-bugs.python.org-issue33895-http.patch#L50 )

**Comment by mingwandroid** [comment]
3.7 doesn't need this patch. Arguably 3.8 doesn't either now. Still, any other lib that calls into the Python DSO from any static initialization will result in the exact same problem and I kind of feel that we should keep our Python patched until this issue has been shaken out of the Windows/Python 3.8 ecosystem. Alternatively we could change my default to go along with upstream and keep the env var around as a way to test for this particular problem if we suspect we have run into it again.

Thoughts welcome!
