### ISSUE TITLE
Use conda-forge's `pybind11` and `pybind11_abi`

### ISSUE THREAD

**Issue by wolfv** [conda-forge/lief-feedstock#27]
So it seems that `py-lief` is using `pybind11` for the python bindings. `mamba` is also using `pybind11` to bind to `libmamba`.
However, `mamba` is using the `pybind11` from `conda-forge` and I think that `py-lief` is either vendoring or ad-hoc downloading `pybind11` because I couldn't find it in the dependencies of the meta.yaml.

There is a weird segfault happening in rare cases when using `mambabuild` on Windows (cf. https://github.com/mamba-org/boa/issues/235 and https://github.com/mamba-org/boa/issues/197) and I think it might be related to two different versions of `pybind11`. It fails during the packaging stage. I added a bunch of `print` statements to the conda-build code and I am pretty sure it's in the inspect linkages step. 

I'll try to modify this recipe to patch out the internal pybind11 and use the proper conda-forge one + the `pybind11_abi` package.

**Comment by mbargull** [comment]
`py-lief=0.14.1` uses (a vendored version of) `nanobind`, so we can mark this issue as outdated.
