### ISSUE TITLE
install lib files in PREFIX/Library on win32

### ISSUE THREAD

**Issue by jschueller** [conda-forge/lief-feedstock#37]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

on windows lib files (dll, includes) must be installed into PREFIX/Library, not directly into PREFIX

### Installed packages

```shell
lief 0.12.3
```

### Environment info

```shell
windows
```

**Comment by mbargull** [comment]
This is now the case for `liblief=0.14.1`.
